### ISSUE TITLE
Dynamic program size

### ISSUE THREAD

**Issue by ngan9elova** [oleksandrbalan/programguide#16]
Hey, so currently I'm trying to implement a dynamic program guide, meaning that at first I will have programs for 4 hours, after scrolling for 8 hours etc., but I get an exception when expanding the size, which I guess it's because of the items size in the minaBox. So, can you let me know if this is intended or is there a way to achieve the dynamic resizing?

`FATAL EXCEPTION: main
                                                                                                    Process: com.appolica.gsandroid.dev, PID: 18501
                                                                                                    java.lang.IllegalArgumentException: width(-404) and height(126) must be >= 0
                                                                                                    	at androidx.compose.ui.unit.Constraints$Companion.fixed-JhjzzOo(Constraints.kt:311)
                                                                                                    	at eu.wewox.minabox.MinaBoxKt$MinaBox$1.invoke-0kLqBqw(MinaBox.kt:86)
                                                                                                    	at eu.wewox.minabox.MinaBoxKt$MinaBox$1.invoke(MinaBox.kt:59)`

**Comment by oleksandrbalan** [comment]
Hi 👋
How did you expand the size? It looks like in some case item's width is going negative, and thus leading to a crash.

**Comment by ngan9elova** [comment]
Just at first I had a list with programs only from 00:00 - 04:00, afterwards on scroll near the end of 04:00, I updated the list and tried adding programs for 04:00 -08:00 and keeping the previous ones as well
